In [3]:
import numpy

In [4]:
import math
import scipy

In [8]:
from numpy import random
import numpy as np
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
print(dataOne)
np.mean(dataOne)

[[0.81913314 0.35920534 0.64359311 0.23579933 0.790839  ]
 [0.84970513 0.94846229 0.31105698 0.9792193  0.94117829]
 [0.00948604 0.97381004 0.84051215 0.42295813 0.69060739]
 [0.14264049 0.58750431 0.12925454 0.03277378 0.39233898]
 [0.89661423 0.72849637 0.64228528 0.08827431 0.27976854]]


0.5494206599739674

In [17]:
# math functions:
x = math.pi
print(x)
y = math.fabs(dataOne[1,1]) #absolute value
z = math.sqrt(dataOne[2,2]) #square root
print(y)
print(z)

3.141592653589793
0.9484622870621829
0.9167944945180209


In [26]:
# stats functions
from scipy import stats
x = scipy.stats.describe(dataOne)
print(x)
y = scipy.stats.tmean(dataOne)
print("mean =", y)
z = scipy.stats.tmax(dataOne)
print(z)

DescribeResult(nobs=5, minmax=(array([0.00948604, 0.35920534, 0.12925454, 0.03277378, 0.27976854]), array([0.89661423, 0.97381004, 0.84051215, 0.9792193 , 0.94117829])), mean=array([0.54351581, 0.71949567, 0.51334041, 0.35180497, 0.61894644]), variance=array([0.18507103, 0.06610334, 0.08226861, 0.14584953, 0.07622707]), skewness=array([-0.43199576, -0.33905102, -0.30280663,  0.97855995, -0.1560619 ]), kurtosis=array([-1.74765919, -1.27751251, -1.36276661, -0.49747607, -1.51820251]))
mean = 0.5494206599739674
[0.89661423 0.97381004 0.84051215 0.9792193  0.94117829]


In [27]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [7]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo #returns error because trying to add a text string to an integer => not allowed
print(varThree)


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [9]:
#Correct way:
varOne = 25
varTwo = 'Hello'
varThree = str(varOne) + varTwo
print(varThree)

25Hello


In [33]:
my_dict = {'black':0, 'white':1, 'blue':-2, 'orange':3, 'red':4}
z = math.sqrt(my_dict['orange'])
print(z)
y = math.fabs(my_dict['blue']) #absolute value
print(y)
x = math.acos(my_dict['black'])
print(x)

1.7320508075688772
2.0
1.5707963267948966


In [41]:
import pandas
data = pandas.read_csv("Blackwell_Hist_Sample.csv")
print(len(data))

10000
